name: Duolingo README Stats

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README
        uses: centrumek/duolingo-readme-stats@v1.0.0
        with:
          DUOLINGO_USER_ID: YOUR_USER_ID
          ADVANCED_TOKEN_JWT: ${{ secrets.DUOLINGO_JWT }}

          SHOW_LANGUAGES: true
          SHOW_LANGUAGES_FROM_ENGLISH: true
          SHOW_STREAK_TIMEZONE: false

          COMMIT_MSG: "chore: update duolingo stats"